### ISSUE TITLE
How do you control the FT-991A?

### ISSUE THREAD

**Issue by po-alima** [rfrht/Voicemeeter-FT-991A#1]
I am using FLRig, but having trouble getting it to play nicely with Voicemeeter.  Will you, please, share your configuration/settings for FLRig?  Thanks.  W6FRI

**Comment by rfrht** [comment]
You mean FLDigi, right?

This is how I've set up the audio

![fldigi](https://user-images.githubusercontent.com/3044503/222541198-5bae7c0e-c7b8-4f01-8c71-5937faf24a06.png)

**Comment by rfrht** [comment]
Closing long stale issue
